### ISSUE TITLE
编码实现界面一——首页 我的书摘

### ISSUE THREAD

**Issue by sixwwg** [laizhiping/teamwork#12]
- [x] 实现文件夹分类功能

- [x] 实现拍照进行识别功能，点击拍摄按钮进入拍照界面

- [x] 点击向下箭头，可以隐藏拍摄按钮、相册导入以及新建文件夹按钮，同时向下箭头变成向上箭头

- [x] 提供对文件夹的上下滑动进行浏览和查找的功能

- [x] 实现相册导入照片进行识别功能，接口实现连接手机相册，点击相册导入按钮，出现手机相册界面

- [x] 实现新建文件夹、删除已有的文件夹、查询某文件夹的功能

- [x] 实现关键字搜索保存的文本以及图片

- [x] 点击某文件夹标题可以进入该文件夹，切换到图片浏览界面

**Comment by laizhiping** [comment]
实现部分
